version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: app12_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app12_user -d app12"]
      interval: 5s
      timeout: 5s
      retries: 5